/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertType = { 'Fire' : null } |
  { 'Safety' : null } |
  { 'Medical' : null } |
  { 'Other' : null };
export interface Apartment {
  'id' : ApartmentId,
  'inchargeId' : [] | [UserId],
  'name' : string,
  'createdAt' : Timestamp,
  'subscriptionStatus' : SubscriptionStatus,
  'address' : string,
  'upiId' : string,
  'upiQrData' : string,
  'superAdminId' : UserId,
}
export interface ApartmentExpense {
  'id' : bigint,
  'status' : ExpenseStatus,
  'apartmentId' : ApartmentId,
  'approvedBy' : Array<UserId>,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : ExpenseCategory,
  'payee' : string,
  'amount' : bigint,
}
export type ApartmentId = bigint;
export interface AppFeedback {
  'id' : bigint,
  'moduleName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
}
export type BillCategory = { 'DTH' : null } |
  { 'Gas' : null } |
  { 'Internet' : null } |
  { 'Electricity' : null } |
  { 'Water' : null } |
  { 'Other' : null };
export interface BillSubscription {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'dueDay' : bigint,
  'category' : BillCategory,
  'amount' : bigint,
  'principalId' : Principal,
}
export interface ChecklistEntry { 'item' : string, 'completed' : boolean }
export type CleaningStatus = { 'Done' : null } |
  { 'Pending' : null };
export interface ConsentRecord {
  'principal' : Principal,
  'watchmanGpsConsent' : [] | [boolean],
  'watchmanPhotoIdConsent' : [] | [boolean],
  'watchmanAttendanceConsent' : [] | [boolean],
  'generalConsent' : boolean,
  'generalConsentAt' : bigint,
  'deviceInfo' : string,
  'phone' : string,
}
export type DebitApprovalStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Executed' : null } |
  { 'Pending' : null };
export interface DisputeNote {
  'note' : string,
  'author' : string,
  'addedAt' : bigint,
}
export interface DisputeRecord {
  'id' : string,
  'status' : string,
  'flatId' : string,
  'createdAt' : bigint,
  'tier' : bigint,
  'description' : string,
  'resolution' : [] | [string],
  'notes' : Array<DisputeNote>,
  'category' : string,
  'resolvedAt' : [] | [bigint],
}
export type DocumentType = { 'PAN' : null } |
  { 'Insurance' : null } |
  { 'Aadhaar' : null } |
  { 'Vehicle' : null } |
  { 'Property' : null } |
  { 'Other' : null };
export interface DocumentVaultEntry {
  'id' : bigint,
  'title' : string,
  'note' : string,
  'docType' : DocumentType,
  'principalId' : Principal,
  'uploadedAt' : Timestamp,
  'fileUrl' : string,
}
export type ExpenseCategory = { 'Repair' : null } |
  { 'Salary' : null } |
  { 'Maintenance' : null } |
  { 'Other' : null } |
  { 'Utilities' : null };
export type ExpenseStatus = { 'Deducted' : null } |
  { 'Approved' : null } |
  { 'Pending' : null };
export interface FacilityStatus {
  'cleaningStatus' : CleaningStatus,
  'apartmentId' : ApartmentId,
  'waterMotorStatus' : WaterMotorStatus,
  'liftStatus' : LiftStatus,
  'lastUpdatedAt' : Timestamp,
  'lastUpdatedBy' : UserId,
  'gateStatus' : GateStatus,
}
export interface FamilyCalendarEvent {
  'id' : bigint,
  'title' : string,
  'reminder' : [] | [Timestamp],
  'date' : Timestamp,
  'time' : string,
  'description' : string,
  'principalId' : Principal,
}
export interface FamilyContact {
  'id' : bigint,
  'relation' : string,
  'name' : string,
  'note' : string,
  'phone' : string,
  'principalId' : Principal,
}
export interface FamilyExpense {
  'id' : bigint,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : FamilyExpenseCategory,
  'amount' : bigint,
  'principalId' : Principal,
}
export type FamilyExpenseCategory = { 'Food' : null } |
  { 'Bills' : null } |
  { 'Grocery' : null } |
  { 'Entertainment' : null } |
  { 'Medical' : null } |
  { 'Other' : null } |
  { 'Transport' : null };
export interface FamilyReminder {
  'id' : bigint,
  'title' : string,
  'repeatType' : RepeatType,
  'date' : Timestamp,
  'time' : string,
  'isActive' : boolean,
  'principalId' : Principal,
}
export interface FamilyTask {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'priority' : TaskPriority,
  'principalId' : Principal,
}
export interface FeedbackRecord {
  'id' : string,
  'userId' : string,
  'feedbackType' : string,
  'submittedAt' : bigint,
  'message' : string,
  'screenshot' : [] | [Uint8Array],
}
export interface Flat {
  'id' : FlatId,
  'status' : FlatStatus,
  'ownerId' : [] | [UserId],
  'apartmentId' : ApartmentId,
  'tenantId' : [] | [UserId],
  'flatNumber' : string,
}
export type FlatId = bigint;
export type FlatStatus = { 'Vacant' : null } |
  { 'Occupied' : null };
export type GateStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'Locked' : null };
export interface GroceryItem {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'isPurchased' : boolean,
  'addedAt' : Timestamp,
  'quantity' : string,
  'principalId' : Principal,
}
export interface GuestRecord {
  'id' : string,
  'expiresAt' : bigint,
  'flatId' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'phone' : string,
}
export interface HandoverChecklist {
  'gateKeyTransferred' : boolean,
  'upiUpdated' : boolean,
  'pendingIssuesNoted' : boolean,
  'ledgerReviewed' : boolean,
}
export interface HealthRecord {
  'id' : bigint,
  'title' : string,
  'date' : Timestamp,
  'note' : string,
  'recordType' : HealthRecordType,
  'memberName' : string,
  'principalId' : Principal,
  'fileUrl' : string,
}
export type HealthRecordType = { 'Vaccination' : null } |
  { 'Report' : null } |
  { 'Other' : null } |
  { 'Prescription' : null };
export interface InchargeRecord {
  'id' : bigint,
  'handoverChecklist' : HandoverChecklist,
  'endDate' : [] | [Timestamp],
  'apartmentId' : ApartmentId,
  'userId' : UserId,
  'isActive' : boolean,
  'handoverNotes' : string,
  'startDate' : Timestamp,
}
export interface Issue {
  'id' : bigint,
  'status' : IssueStatus,
  'title' : string,
  'assignedTo' : [] | [UserId],
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'category' : IssueCategory,
  'raisedBy' : UserId,
  'resolvedAt' : [] | [Timestamp],
}
export type IssueCategory = { 'Security' : null } |
  { 'Plumbing' : null } |
  { 'Maintenance' : null } |
  { 'Electrical' : null } |
  { 'Other' : null } |
  { 'Common' : null };
export type IssueStatus = { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export type LiftStatus = { 'OK' : null } |
  { 'Issue' : null } |
  { 'Offline' : null };
export interface MaintenancePayment {
  'id' : bigint,
  'status' : PaymentStatus,
  'month' : bigint,
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'screenshotUrl' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
  'correctionNote' : [] | [string],
  'correctionOf' : [] | [bigint],
  'utrNumber' : string,
  'amount' : bigint,
  'verifiedBy' : [] | [UserId],
}
export interface MoveOutChecklist {
  'completedAt' : [] | [bigint],
  'flatId' : string,
  'items' : Array<ChecklistEntry>,
  'initiatedAt' : bigint,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'postedAt' : Timestamp,
  'postedBy' : UserId,
  'content' : string,
  'acknowledgedBy' : Array<UserId>,
  'apartmentId' : ApartmentId,
  'priority' : Priority,
}
export interface ParkingSlot {
  'id' : bigint,
  'assignedAt' : [] | [Timestamp],
  'assignedTo' : [] | [FlatId],
  'apartmentId' : ApartmentId,
  'slotType' : ParkingType,
  'slotNumber' : string,
}
export type ParkingType = { 'Car' : null } |
  { 'Bike' : null } |
  { 'Both' : null };
export type PaymentStatus = { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface PendingWatchman {
  'status' : WatchmanStatus,
  'principal' : Principal,
  'docUrl' : string,
  'apartmentId' : string,
  'userId' : string,
  'name' : string,
  'rejectionReason' : [] | [string],
  'submittedAt' : bigint,
  'phone' : string,
  'docType' : WatchmanIdType,
  'uploadedAt' : bigint,
}
export interface PlatformHealth {
  'activeUsers' : bigint,
  'cycleBalance' : bigint,
  'failedLogins' : bigint,
  'uptimePercent' : bigint,
  'sosCount' : bigint,
}
export type Priority = { 'Important' : null } |
  { 'Normal' : null } |
  { 'Urgent' : null };
export interface ProfileInfo {
  'apartmentId' : string,
  'flatId' : [] | [string],
  'userId' : string,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
}
export type RepeatType = { 'Weekly' : null } |
  { 'None' : null } |
  { 'Daily' : null } |
  { 'Monthly' : null };
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : { 'role' : string, 'isValid' : boolean } } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_3 = { 'ok' : ProfileInfo } |
  { 'err' : string };
export type Result_4 = { 'ok' : Array<TicketMessage> } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<SupportTicket> } |
  { 'err' : string };
export type Result_6 = {
    'ok' : { 'expiresAt' : bigint, 'code' : string, 'link' : string }
  } |
  { 'err' : string };
export type Result_7 = { 'ok' : { 'code' : string, 'link' : string } } |
  { 'err' : string };
export type Role = { 'RotatingIncharge' : null } |
  { 'Guest' : null } |
  { 'FamilyMember' : null } |
  { 'Employee' : null } |
  { 'Founder' : null } |
  { 'CoFounder' : null } |
  { 'SuperAdmin' : null } |
  { 'FlatAdmin' : null } |
  { 'Freelancer' : null } |
  { 'WatchmanFamily' : null } |
  { 'Watchman' : null } |
  { 'Contractor' : null };
export interface SOSAlert {
  'id' : bigint,
  'resolutionNote' : string,
  'alertType' : AlertType,
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'isFalseAlarm' : boolean,
  'falseAlarmReason' : string,
  'triggeredAt' : Timestamp,
  'triggeredBy' : UserId,
  'respondedAt' : [] | [Timestamp],
  'respondedBy' : [] | [UserId],
  'resolvedAt' : [] | [Timestamp],
  'resolvedBy' : [] | [UserId],
}
export interface ShiftHandoverChecklist {
  'liftChecked' : boolean,
  'gateChecked' : boolean,
  'motorChecked' : boolean,
}
export interface SlaMetadata {
  'resolutionSla' : Timestamp,
  'firstResponseSla' : Timestamp,
  'breached' : boolean,
  'firstResponseAt' : [] | [Timestamp],
  'resolvedAt' : [] | [Timestamp],
}
export interface SubscriptionRow {
  'status' : SubscriptionStatus,
  'apartmentId' : ApartmentId,
  'city' : string,
  'dueDate' : Timestamp,
  'adminUserId' : UserId,
  'utrSubmitted' : boolean,
  'flatsCount' : bigint,
  'apartmentName' : string,
}
export type SubscriptionStatus = { 'GracePeriod' : null } |
  { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Overdue' : null } |
  { 'Trial' : null };
export interface SupportTicket {
  'id' : bigint,
  'sla' : SlaMetadata,
  'status' : TicketStatus,
  'assignedTo' : [] | [UserId],
  'subject' : string,
  'apartmentId' : [] | [ApartmentId],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'ticketType' : TicketType,
  'category' : TicketCategory,
  'priority' : TicketPriority,
}
export type TaskPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type TaskStatus = { 'Done' : null } |
  { 'Pending' : null };
export type TicketCategory = { 'Bug' : null } |
  { 'Technical' : null } |
  { 'Billing' : null } |
  { 'Account' : null } |
  { 'Dispute' : null } |
  { 'Payment' : null } |
  { 'Other' : null } |
  { 'Feature' : null };
export interface TicketMessage {
  'id' : bigint,
  'attachmentUrl' : [] | [string],
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'ticketId' : bigint,
  'message' : string,
  'isInternal' : boolean,
}
export type TicketPriority = { 'Normal' : null } |
  { 'Urgent' : null };
export type TicketStatus = { 'WaitingForUser' : null } |
  { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export type TicketType = { 'Support' : null } |
  { 'DisputeEscalation' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'principal' : Principal,
  'apartmentId' : [] | [ApartmentId],
  'flatId' : [] | [FlatId],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : boolean,
  'phone' : string,
}
export type UserId = bigint;
export interface VisitorEntry {
  'id' : bigint,
  'apartmentId' : ApartmentId,
  'flatId' : [] | [FlatId],
  'note' : string,
  'visitorName' : string,
  'visitorType' : VisitorType,
  'enteredAt' : Timestamp,
  'enteredBy' : UserId,
}
export type VisitorType = { 'Guest' : null } |
  { 'Delivery' : null } |
  { 'Unknown' : null } |
  { 'Service' : null };
export interface WalletEntry {
  'id' : bigint,
  'status' : DebitApprovalStatus,
  'entryType' : WalletEntryType,
  'apartmentId' : ApartmentId,
  'flatId' : [] | [FlatId],
  'approvedBy' : Array<UserId>,
  'createdAt' : Timestamp,
  'correctionNote' : [] | [string],
  'correctionOf' : [] | [bigint],
  'utrNumber' : [] | [string],
  'amount' : bigint,
  'purpose' : string,
  'isPermanent' : boolean,
}
export type WalletEntryType = { 'Debit' : null } |
  { 'Correction' : null } |
  { 'Credit' : null };
export interface WatchmanFamilyMember {
  'id' : string,
  'name' : string,
  'isActive' : boolean,
  'phone' : string,
  'watchmanId' : string,
}
export type WatchmanIdType = { 'Passport' : null } |
  { 'Aadhaar' : null } |
  { 'DrivingLicence' : null } |
  { 'VoterID' : null } |
  { 'Other' : null };
export interface WatchmanShift {
  'id' : bigint,
  'startedAt' : Timestamp,
  'handoverChecklist' : ShiftHandoverChecklist,
  'apartmentId' : ApartmentId,
  'endedAt' : [] | [Timestamp],
  'isNightMode' : boolean,
  'relievedById' : [] | [UserId],
  'handoverNote' : string,
  'watchmanId' : UserId,
}
export type WatchmanStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type WaterMotorStatus = { 'On' : null } |
  { 'Off' : null };
export interface _SERVICE {
  'acceptHandover' : ActorMethod<[ApartmentId, UserId], Result>,
  'acknowledgeNotice' : ActorMethod<[bigint], Result>,
  'addBillSubscription' : ActorMethod<
    [string, bigint, bigint, BillCategory],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addCalendarEvent' : ActorMethod<
    [string, string, Timestamp, string, [] | [Timestamp]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addCorrectionEntry' : ActorMethod<
    [bigint, string, [] | [bigint], string],
    Result
  >,
  'addDisputeNote' : ActorMethod<
    [string, string, [] | [Uint8Array]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addDocument' : ActorMethod<
    [string, DocumentType, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFamilyContact' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFamilyExpense' : ActorMethod<
    [bigint, FamilyExpenseCategory, string, Timestamp],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addFamilyTask' : ActorMethod<
    [string, string, string, [] | [Timestamp], TaskPriority],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addGroceryItem' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addHealthRecord' : ActorMethod<
    [string, HealthRecordType, string, string, Timestamp, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addInternalNote' : ActorMethod<[bigint, string], Result>,
  'addMessage' : ActorMethod<[bigint, string], Result>,
  'addReminder' : ActorMethod<
    [string, Timestamp, string, RepeatType],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addWatchmanFamilyMember' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approveDebit' : ActorMethod<[bigint], Result>,
  'approveExpense' : ActorMethod<[bigint], Result>,
  'approveWatchmanId' : ActorMethod<[Principal], Result>,
  'assignIncharge' : ActorMethod<[ApartmentId, UserId, Timestamp], Result>,
  'assignParking' : ActorMethod<[bigint, FlatId], Result>,
  'assignRole' : ActorMethod<[Principal, Role], Result>,
  'completeChecklistItem' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'completeMovOut' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createApartment' : ActorMethod<[string, string], Result>,
  'createDispute' : ActorMethod<
    [string, string, string, [] | [Uint8Array]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createExpense' : ActorMethod<
    [ApartmentId, bigint, ExpenseCategory, string, string],
    Result
  >,
  'createFlat' : ActorMethod<[ApartmentId, string], Result>,
  'createGuest' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createTicket' : ActorMethod<
    [string, string, TicketCategory, TicketPriority, TicketType],
    Result
  >,
  'createWatchmanInvite' : ActorMethod<[string, string], Result>,
  'deactivateUser' : ActorMethod<[Principal], Result>,
  'deductExpense' : ActorMethod<[bigint], Result>,
  'deleteBillSubscription' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteCalendarEvent' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteDocument' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteFamilyContact' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteFamilyExpense' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteFamilyTask' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteGroceryItem' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteHealthRecord' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteReminder' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'endShift' : ActorMethod<[bigint, string, ShiftHandoverChecklist], Result>,
  'escalateDispute' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateFounderInvite' : ActorMethod<[string], Result_7>,
  'generateInviteCode' : ActorMethod<[string, [] | [string]], Result_6>,
  'getActiveShift' : ActorMethod<[ApartmentId], [] | [WatchmanShift]>,
  'getActiveUpiId' : ActorMethod<
    [ApartmentId],
    [] | [
      {
        'qrImageUrl' : [] | [string],
        'upiId' : string,
        'effectiveFrom' : bigint,
      }
    ]
  >,
  'getApartment' : ActorMethod<[ApartmentId], [] | [Apartment]>,
  'getApartmentCount' : ActorMethod<[], bigint>,
  'getApartmentOverview' : ActorMethod<
    [],
    Array<
      {
        'apartmentId' : ApartmentId,
        'city' : string,
        'name' : string,
        'subscriptionStatus' : SubscriptionStatus,
        'superAdminId' : UserId,
      }
    >
  >,
  'getApartmentUsers' : ActorMethod<[ApartmentId], Array<User>>,
  'getConsentRecord' : ActorMethod<[string], [] | [ConsentRecord]>,
  'getDisputeEscalations' : ActorMethod<[], Result_5>,
  'getDisputes' : ActorMethod<[[] | [string]], Array<DisputeRecord>>,
  'getExpenses' : ActorMethod<[ApartmentId], Array<ApartmentExpense>>,
  'getFacilityStatus' : ActorMethod<[ApartmentId], [] | [FacilityStatus]>,
  'getFeedback' : ActorMethod<[], Array<AppFeedback>>,
  'getFlats' : ActorMethod<[ApartmentId], Array<Flat>>,
  'getFounderTeam' : ActorMethod<[], Array<ProfileInfo>>,
  'getGuests' : ActorMethod<[string], Array<GuestRecord>>,
  'getInAppFeedback' : ActorMethod<[[] | [string]], Array<FeedbackRecord>>,
  'getInchargeHistory' : ActorMethod<[ApartmentId], Array<InchargeRecord>>,
  'getIssues' : ActorMethod<[ApartmentId], Array<Issue>>,
  'getIssuesByFlat' : ActorMethod<[FlatId], Array<Issue>>,
  'getMaintenanceForFlat' : ActorMethod<[FlatId], Array<MaintenancePayment>>,
  'getMoveOutChecklist' : ActorMethod<[string], [] | [MoveOutChecklist]>,
  'getMyMaintenancePayments' : ActorMethod<[], Array<MaintenancePayment>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getMyRole' : ActorMethod<[], [] | [string]>,
  'getNotices' : ActorMethod<[ApartmentId], Array<Notice>>,
  'getNoticesForApartment' : ActorMethod<[ApartmentId], Array<Notice>>,
  'getNoticesForFamily' : ActorMethod<[], Array<Notice>>,
  'getOpenTicketCount' : ActorMethod<[], bigint>,
  'getParkingSlots' : ActorMethod<[ApartmentId], Array<ParkingSlot>>,
  'getPaymentsByFlat' : ActorMethod<[FlatId], Array<MaintenancePayment>>,
  'getPendingPaymentConfirmations' : ActorMethod<[], bigint>,
  'getPendingPayments' : ActorMethod<[ApartmentId], Array<MaintenancePayment>>,
  'getPendingWatchmanApprovals' : ActorMethod<[], Array<PendingWatchman>>,
  'getPlatformHealth' : ActorMethod<[], PlatformHealth>,
  'getSOSLog' : ActorMethod<[ApartmentId], Array<SOSAlert>>,
  'getShiftHistory' : ActorMethod<[ApartmentId], Array<WatchmanShift>>,
  'getSubscriptionTable' : ActorMethod<[], Array<SubscriptionRow>>,
  'getSubscriptionsDueThisWeek' : ActorMethod<[], bigint>,
  'getTicketThread' : ActorMethod<[bigint], Result_4>,
  'getTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getUnreadNoticeCount' : ActorMethod<[ApartmentId], bigint>,
  'getVisitorLog' : ActorMethod<[ApartmentId], Array<VisitorEntry>>,
  'getVisitorLogForFlat' : ActorMethod<[FlatId], Array<VisitorEntry>>,
  'getWalletBalance' : ActorMethod<[ApartmentId], bigint>,
  'getWalletLedger' : ActorMethod<[ApartmentId], Array<WalletEntry>>,
  'getWalletSummaryForRole' : ActorMethod<
    [ApartmentId],
    {
      'balance' : bigint,
      'totalCollected' : bigint,
      'entries' : [] | [Array<WalletEntry>],
      'totalSpent' : bigint,
    }
  >,
  'getWatchmanFamily' : ActorMethod<[string], Array<WatchmanFamilyMember>>,
  'initiateDebit' : ActorMethod<[ApartmentId, bigint, string], Result>,
  'initiateHandover' : ActorMethod<
    [ApartmentId, string, HandoverChecklist],
    Result
  >,
  'initiateMovIn' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'initiateMovOut' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'isFounderRegistered' : ActorMethod<[], boolean>,
  'listBillSubscriptions' : ActorMethod<[], Array<BillSubscription>>,
  'listCalendarEvents' : ActorMethod<[], Array<FamilyCalendarEvent>>,
  'listDocuments' : ActorMethod<[], Array<DocumentVaultEntry>>,
  'listFamilyContacts' : ActorMethod<[], Array<FamilyContact>>,
  'listFamilyExpenses' : ActorMethod<[], Array<FamilyExpense>>,
  'listFamilyTasks' : ActorMethod<[], Array<FamilyTask>>,
  'listGroceryItems' : ActorMethod<[], Array<GroceryItem>>,
  'listHealthRecords' : ActorMethod<[], Array<HealthRecord>>,
  'listReminders' : ActorMethod<[], Array<FamilyReminder>>,
  'logVisitor' : ActorMethod<
    [[] | [FlatId], ApartmentId, string, VisitorType, string],
    Result
  >,
  'loginWithII' : ActorMethod<[], Result_3>,
  'markResolved' : ActorMethod<[bigint, string], Result_2>,
  'postNotice' : ActorMethod<[ApartmentId, string, string, Priority], Result>,
  'raiseIssue' : ActorMethod<
    [FlatId, ApartmentId, string, string, IssueCategory],
    Result
  >,
  'recordConsent' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerApartment' : ActorMethod<[string, string], Result>,
  'registerWithInvite' : ActorMethod<[string, string, string], Result>,
  'rejectDebit' : ActorMethod<[bigint, string], Result_2>,
  'rejectWatchmanId' : ActorMethod<[Principal, string], Result>,
  'reopenTicket' : ActorMethod<[bigint, string], Result_2>,
  'resolveDispute' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resolveSOS' : ActorMethod<[bigint, string, boolean, string], Result>,
  'respondToSOS' : ActorMethod<[bigint], Result>,
  'revokeGuest' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setNightMode' : ActorMethod<[bigint, boolean], Result>,
  'setUpiId' : ActorMethod<[string, [] | [string]], Result>,
  'startShift' : ActorMethod<[ApartmentId, UserId], Result>,
  'submitFeedback' : ActorMethod<[bigint, string, string], Result>,
  'submitInAppFeedback' : ActorMethod<
    [string, string, [] | [Uint8Array]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitPayment' : ActorMethod<
    [FlatId, ApartmentId, bigint, bigint, bigint, string, string],
    Result
  >,
  'submitWatchmanIdDoc' : ActorMethod<[string, WatchmanIdType], Result>,
  'triggerSOS' : ActorMethod<[FlatId, ApartmentId, AlertType], Result>,
  'unassignParking' : ActorMethod<[bigint], Result>,
  'updateApartmentUpi' : ActorMethod<[ApartmentId, string, string], Result>,
  'updateBillSubscription' : ActorMethod<
    [bigint, string, bigint, bigint, BillCategory, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateFacilityStatus' : ActorMethod<
    [ApartmentId, GateStatus, WaterMotorStatus, LiftStatus, CleaningStatus],
    Result
  >,
  'updateFamilyContact' : ActorMethod<
    [bigint, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateFamilyExpense' : ActorMethod<
    [bigint, bigint, FamilyExpenseCategory, string, Timestamp],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateFamilyTask' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [Timestamp],
      TaskStatus,
      TaskPriority,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateGroceryItem' : ActorMethod<
    [bigint, string, string, string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateIssueStatus' : ActorMethod<[bigint, IssueStatus], Result>,
  'updateTicketStatus' : ActorMethod<[bigint, TicketStatus], Result>,
  'validateInviteCode' : ActorMethod<[string], Result_1>,
  'verifyPayment' : ActorMethod<[bigint, boolean], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];