/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApartmentId = IDL.Nat;
export const UserId = IDL.Nat;
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const BillCategory = IDL.Variant({
  'DTH' : IDL.Null,
  'Gas' : IDL.Null,
  'Internet' : IDL.Null,
  'Electricity' : IDL.Null,
  'Water' : IDL.Null,
  'Other' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const DocumentType = IDL.Variant({
  'PAN' : IDL.Null,
  'Insurance' : IDL.Null,
  'Aadhaar' : IDL.Null,
  'Vehicle' : IDL.Null,
  'Property' : IDL.Null,
  'Other' : IDL.Null,
});
export const FamilyExpenseCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Bills' : IDL.Null,
  'Grocery' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Medical' : IDL.Null,
  'Other' : IDL.Null,
  'Transport' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const HealthRecordType = IDL.Variant({
  'Vaccination' : IDL.Null,
  'Report' : IDL.Null,
  'Other' : IDL.Null,
  'Prescription' : IDL.Null,
});
export const RepeatType = IDL.Variant({
  'Weekly' : IDL.Null,
  'None' : IDL.Null,
  'Daily' : IDL.Null,
  'Monthly' : IDL.Null,
});
export const FlatId = IDL.Nat;
export const Role = IDL.Variant({
  'RotatingIncharge' : IDL.Null,
  'Guest' : IDL.Null,
  'FamilyMember' : IDL.Null,
  'Employee' : IDL.Null,
  'Founder' : IDL.Null,
  'CoFounder' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'FlatAdmin' : IDL.Null,
  'Freelancer' : IDL.Null,
  'WatchmanFamily' : IDL.Null,
  'Watchman' : IDL.Null,
  'Contractor' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'Repair' : IDL.Null,
  'Salary' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Other' : IDL.Null,
  'Utilities' : IDL.Null,
});
export const TicketCategory = IDL.Variant({
  'Bug' : IDL.Null,
  'Technical' : IDL.Null,
  'Billing' : IDL.Null,
  'Account' : IDL.Null,
  'Dispute' : IDL.Null,
  'Payment' : IDL.Null,
  'Other' : IDL.Null,
  'Feature' : IDL.Null,
});
export const TicketPriority = IDL.Variant({
  'Normal' : IDL.Null,
  'Urgent' : IDL.Null,
});
export const TicketType = IDL.Variant({
  'Support' : IDL.Null,
  'DisputeEscalation' : IDL.Null,
});
export const ShiftHandoverChecklist = IDL.Record({
  'liftChecked' : IDL.Bool,
  'gateChecked' : IDL.Bool,
  'motorChecked' : IDL.Bool,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Record({ 'code' : IDL.Text, 'link' : IDL.Text }),
  'err' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Record({
    'expiresAt' : IDL.Int,
    'code' : IDL.Text,
    'link' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const WatchmanShift = IDL.Record({
  'id' : IDL.Nat,
  'startedAt' : Timestamp,
  'handoverChecklist' : ShiftHandoverChecklist,
  'apartmentId' : ApartmentId,
  'endedAt' : IDL.Opt(Timestamp),
  'isNightMode' : IDL.Bool,
  'relievedById' : IDL.Opt(UserId),
  'handoverNote' : IDL.Text,
  'watchmanId' : UserId,
});
export const SubscriptionStatus = IDL.Variant({
  'GracePeriod' : IDL.Null,
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Overdue' : IDL.Null,
  'Trial' : IDL.Null,
});
export const Apartment = IDL.Record({
  'id' : ApartmentId,
  'inchargeId' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'subscriptionStatus' : SubscriptionStatus,
  'address' : IDL.Text,
  'upiId' : IDL.Text,
  'upiQrData' : IDL.Text,
  'superAdminId' : UserId,
});
export const User = IDL.Record({
  'id' : UserId,
  'principal' : IDL.Principal,
  'apartmentId' : IDL.Opt(ApartmentId),
  'flatId' : IDL.Opt(FlatId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
});
export const ConsentRecord = IDL.Record({
  'principal' : IDL.Principal,
  'watchmanGpsConsent' : IDL.Opt(IDL.Bool),
  'watchmanPhotoIdConsent' : IDL.Opt(IDL.Bool),
  'watchmanAttendanceConsent' : IDL.Opt(IDL.Bool),
  'generalConsent' : IDL.Bool,
  'generalConsentAt' : IDL.Int,
  'deviceInfo' : IDL.Text,
  'phone' : IDL.Text,
});
export const SlaMetadata = IDL.Record({
  'resolutionSla' : Timestamp,
  'firstResponseSla' : Timestamp,
  'breached' : IDL.Bool,
  'firstResponseAt' : IDL.Opt(Timestamp),
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const TicketStatus = IDL.Variant({
  'WaitingForUser' : IDL.Null,
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'sla' : SlaMetadata,
  'status' : TicketStatus,
  'assignedTo' : IDL.Opt(UserId),
  'subject' : IDL.Text,
  'apartmentId' : IDL.Opt(ApartmentId),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'ticketType' : TicketType,
  'category' : TicketCategory,
  'priority' : TicketPriority,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(SupportTicket),
  'err' : IDL.Text,
});
export const DisputeNote = IDL.Record({
  'note' : IDL.Text,
  'author' : IDL.Text,
  'addedAt' : IDL.Int,
});
export const DisputeRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'flatId' : IDL.Text,
  'createdAt' : IDL.Int,
  'tier' : IDL.Nat,
  'description' : IDL.Text,
  'resolution' : IDL.Opt(IDL.Text),
  'notes' : IDL.Vec(DisputeNote),
  'category' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const ExpenseStatus = IDL.Variant({
  'Deducted' : IDL.Null,
  'Approved' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ApartmentExpense = IDL.Record({
  'id' : IDL.Nat,
  'status' : ExpenseStatus,
  'apartmentId' : ApartmentId,
  'approvedBy' : IDL.Vec(UserId),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : ExpenseCategory,
  'payee' : IDL.Text,
  'amount' : IDL.Nat,
});
export const CleaningStatus = IDL.Variant({
  'Done' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WaterMotorStatus = IDL.Variant({
  'On' : IDL.Null,
  'Off' : IDL.Null,
});
export const LiftStatus = IDL.Variant({
  'OK' : IDL.Null,
  'Issue' : IDL.Null,
  'Offline' : IDL.Null,
});
export const GateStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'Locked' : IDL.Null,
});
export const FacilityStatus = IDL.Record({
  'cleaningStatus' : CleaningStatus,
  'apartmentId' : ApartmentId,
  'waterMotorStatus' : WaterMotorStatus,
  'liftStatus' : LiftStatus,
  'lastUpdatedAt' : Timestamp,
  'lastUpdatedBy' : UserId,
  'gateStatus' : GateStatus,
});
export const AppFeedback = IDL.Record({
  'id' : IDL.Nat,
  'moduleName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const FlatStatus = IDL.Variant({
  'Vacant' : IDL.Null,
  'Occupied' : IDL.Null,
});
export const Flat = IDL.Record({
  'id' : FlatId,
  'status' : FlatStatus,
  'ownerId' : IDL.Opt(UserId),
  'apartmentId' : ApartmentId,
  'tenantId' : IDL.Opt(UserId),
  'flatNumber' : IDL.Text,
});
export const ProfileInfo = IDL.Record({
  'apartmentId' : IDL.Text,
  'flatId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const GuestRecord = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Int,
  'flatId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
});
export const FeedbackRecord = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'feedbackType' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Text,
  'screenshot' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const HandoverChecklist = IDL.Record({
  'gateKeyTransferred' : IDL.Bool,
  'upiUpdated' : IDL.Bool,
  'pendingIssuesNoted' : IDL.Bool,
  'ledgerReviewed' : IDL.Bool,
});
export const InchargeRecord = IDL.Record({
  'id' : IDL.Nat,
  'handoverChecklist' : HandoverChecklist,
  'endDate' : IDL.Opt(Timestamp),
  'apartmentId' : ApartmentId,
  'userId' : UserId,
  'isActive' : IDL.Bool,
  'handoverNotes' : IDL.Text,
  'startDate' : Timestamp,
});
export const IssueStatus = IDL.Variant({
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const IssueCategory = IDL.Variant({
  'Security' : IDL.Null,
  'Plumbing' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
  'Common' : IDL.Null,
});
export const Issue = IDL.Record({
  'id' : IDL.Nat,
  'status' : IssueStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(UserId),
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : IssueCategory,
  'raisedBy' : UserId,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const PaymentStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const MaintenancePayment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'month' : IDL.Nat,
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'screenshotUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'correctionNote' : IDL.Opt(IDL.Text),
  'correctionOf' : IDL.Opt(IDL.Nat),
  'utrNumber' : IDL.Text,
  'amount' : IDL.Nat,
  'verifiedBy' : IDL.Opt(UserId),
});
export const ChecklistEntry = IDL.Record({
  'item' : IDL.Text,
  'completed' : IDL.Bool,
});
export const MoveOutChecklist = IDL.Record({
  'completedAt' : IDL.Opt(IDL.Int),
  'flatId' : IDL.Text,
  'items' : IDL.Vec(ChecklistEntry),
  'initiatedAt' : IDL.Int,
});
export const Priority = IDL.Variant({
  'Important' : IDL.Null,
  'Normal' : IDL.Null,
  'Urgent' : IDL.Null,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'postedBy' : UserId,
  'content' : IDL.Text,
  'acknowledgedBy' : IDL.Vec(UserId),
  'apartmentId' : ApartmentId,
  'priority' : Priority,
});
export const ParkingType = IDL.Variant({
  'Car' : IDL.Null,
  'Bike' : IDL.Null,
  'Both' : IDL.Null,
});
export const ParkingSlot = IDL.Record({
  'id' : IDL.Nat,
  'assignedAt' : IDL.Opt(Timestamp),
  'assignedTo' : IDL.Opt(FlatId),
  'apartmentId' : ApartmentId,
  'slotType' : ParkingType,
  'slotNumber' : IDL.Text,
});
export const WatchmanStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WatchmanIdType = IDL.Variant({
  'Passport' : IDL.Null,
  'Aadhaar' : IDL.Null,
  'DrivingLicence' : IDL.Null,
  'VoterID' : IDL.Null,
  'Other' : IDL.Null,
});
export const PendingWatchman = IDL.Record({
  'status' : WatchmanStatus,
  'principal' : IDL.Principal,
  'docUrl' : IDL.Text,
  'apartmentId' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'phone' : IDL.Text,
  'docType' : WatchmanIdType,
  'uploadedAt' : IDL.Int,
});
export const PlatformHealth = IDL.Record({
  'activeUsers' : IDL.Nat,
  'cycleBalance' : IDL.Nat,
  'failedLogins' : IDL.Nat,
  'uptimePercent' : IDL.Nat,
  'sosCount' : IDL.Nat,
});
export const AlertType = IDL.Variant({
  'Fire' : IDL.Null,
  'Safety' : IDL.Null,
  'Medical' : IDL.Null,
  'Other' : IDL.Null,
});
export const SOSAlert = IDL.Record({
  'id' : IDL.Nat,
  'resolutionNote' : IDL.Text,
  'alertType' : AlertType,
  'apartmentId' : ApartmentId,
  'flatId' : FlatId,
  'isFalseAlarm' : IDL.Bool,
  'falseAlarmReason' : IDL.Text,
  'triggeredAt' : Timestamp,
  'triggeredBy' : UserId,
  'respondedAt' : IDL.Opt(Timestamp),
  'respondedBy' : IDL.Opt(UserId),
  'resolvedAt' : IDL.Opt(Timestamp),
  'resolvedBy' : IDL.Opt(UserId),
});
export const SubscriptionRow = IDL.Record({
  'status' : SubscriptionStatus,
  'apartmentId' : ApartmentId,
  'city' : IDL.Text,
  'dueDate' : Timestamp,
  'adminUserId' : UserId,
  'utrSubmitted' : IDL.Bool,
  'flatsCount' : IDL.Nat,
  'apartmentName' : IDL.Text,
});
export const TicketMessage = IDL.Record({
  'id' : IDL.Nat,
  'attachmentUrl' : IDL.Opt(IDL.Text),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'ticketId' : IDL.Nat,
  'message' : IDL.Text,
  'isInternal' : IDL.Bool,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(TicketMessage),
  'err' : IDL.Text,
});
export const VisitorType = IDL.Variant({
  'Guest' : IDL.Null,
  'Delivery' : IDL.Null,
  'Unknown' : IDL.Null,
  'Service' : IDL.Null,
});
export const VisitorEntry = IDL.Record({
  'id' : IDL.Nat,
  'apartmentId' : ApartmentId,
  'flatId' : IDL.Opt(FlatId),
  'note' : IDL.Text,
  'visitorName' : IDL.Text,
  'visitorType' : VisitorType,
  'enteredAt' : Timestamp,
  'enteredBy' : UserId,
});
export const DebitApprovalStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Executed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WalletEntryType = IDL.Variant({
  'Debit' : IDL.Null,
  'Correction' : IDL.Null,
  'Credit' : IDL.Null,
});
export const WalletEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : DebitApprovalStatus,
  'entryType' : WalletEntryType,
  'apartmentId' : ApartmentId,
  'flatId' : IDL.Opt(FlatId),
  'approvedBy' : IDL.Vec(UserId),
  'createdAt' : Timestamp,
  'correctionNote' : IDL.Opt(IDL.Text),
  'correctionOf' : IDL.Opt(IDL.Nat),
  'utrNumber' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'purpose' : IDL.Text,
  'isPermanent' : IDL.Bool,
});
export const WatchmanFamilyMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'phone' : IDL.Text,
  'watchmanId' : IDL.Text,
});
export const BillSubscription = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'dueDay' : IDL.Nat,
  'category' : BillCategory,
  'amount' : IDL.Nat,
  'principalId' : IDL.Principal,
});
export const FamilyCalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'reminder' : IDL.Opt(Timestamp),
  'date' : Timestamp,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const DocumentVaultEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'note' : IDL.Text,
  'docType' : DocumentType,
  'principalId' : IDL.Principal,
  'uploadedAt' : Timestamp,
  'fileUrl' : IDL.Text,
});
export const FamilyContact = IDL.Record({
  'id' : IDL.Nat,
  'relation' : IDL.Text,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'phone' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const FamilyExpense = IDL.Record({
  'id' : IDL.Nat,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : FamilyExpenseCategory,
  'amount' : IDL.Nat,
  'principalId' : IDL.Principal,
});
export const TaskStatus = IDL.Variant({
  'Done' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FamilyTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'priority' : TaskPriority,
  'principalId' : IDL.Principal,
});
export const GroceryItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'isPurchased' : IDL.Bool,
  'addedAt' : Timestamp,
  'quantity' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Timestamp,
  'note' : IDL.Text,
  'recordType' : HealthRecordType,
  'memberName' : IDL.Text,
  'principalId' : IDL.Principal,
  'fileUrl' : IDL.Text,
});
export const FamilyReminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'repeatType' : RepeatType,
  'date' : Timestamp,
  'time' : IDL.Text,
  'isActive' : IDL.Bool,
  'principalId' : IDL.Principal,
});
export const Result_3 = IDL.Variant({ 'ok' : ProfileInfo, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({
  'ok' : IDL.Record({ 'role' : IDL.Text, 'isValid' : IDL.Bool }),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'acceptHandover' : IDL.Func([ApartmentId, UserId], [Result], []),
  'acknowledgeNotice' : IDL.Func([IDL.Nat], [Result], []),
  'addBillSubscription' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, BillCategory],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addCalendarEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Text, IDL.Opt(Timestamp)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addCorrectionEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [Result],
      [],
    ),
  'addDisputeNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addDocument' : IDL.Func(
      [IDL.Text, DocumentType, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addFamilyContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addFamilyExpense' : IDL.Func(
      [IDL.Nat, FamilyExpenseCategory, IDL.Text, Timestamp],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addFamilyTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Timestamp), TaskPriority],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addGroceryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addHealthRecord' : IDL.Func(
      [IDL.Text, HealthRecordType, IDL.Text, IDL.Text, Timestamp, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addInternalNote' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'addMessage' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'addReminder' : IDL.Func(
      [IDL.Text, Timestamp, IDL.Text, RepeatType],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addWatchmanFamilyMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'approveDebit' : IDL.Func([IDL.Nat], [Result], []),
  'approveExpense' : IDL.Func([IDL.Nat], [Result], []),
  'approveWatchmanId' : IDL.Func([IDL.Principal], [Result], []),
  'assignIncharge' : IDL.Func([ApartmentId, UserId, Timestamp], [Result], []),
  'assignParking' : IDL.Func([IDL.Nat, FlatId], [Result], []),
  'assignRole' : IDL.Func([IDL.Principal, Role], [Result], []),
  'completeChecklistItem' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'completeMovOut' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createApartment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'createDispute' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createExpense' : IDL.Func(
      [ApartmentId, IDL.Nat, ExpenseCategory, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'createFlat' : IDL.Func([ApartmentId, IDL.Text], [Result], []),
  'createGuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createTicket' : IDL.Func(
      [IDL.Text, IDL.Text, TicketCategory, TicketPriority, TicketType],
      [Result],
      [],
    ),
  'createWatchmanInvite' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [Result], []),
  'deductExpense' : IDL.Func([IDL.Nat], [Result], []),
  'deleteBillSubscription' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteCalendarEvent' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteDocument' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteFamilyContact' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteFamilyExpense' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteFamilyTask' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteGroceryItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteHealthRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteReminder' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'endShift' : IDL.Func(
      [IDL.Nat, IDL.Text, ShiftHandoverChecklist],
      [Result],
      [],
    ),
  'escalateDispute' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateFounderInvite' : IDL.Func([IDL.Text], [Result_7], []),
  'generateInviteCode' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [Result_6],
      [],
    ),
  'getActiveShift' : IDL.Func(
      [ApartmentId],
      [IDL.Opt(WatchmanShift)],
      ['query'],
    ),
  'getActiveUpiId' : IDL.Func(
      [ApartmentId],
      [
        IDL.Opt(
          IDL.Record({
            'qrImageUrl' : IDL.Opt(IDL.Text),
            'upiId' : IDL.Text,
            'effectiveFrom' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getApartment' : IDL.Func([ApartmentId], [IDL.Opt(Apartment)], ['query']),
  'getApartmentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getApartmentOverview' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'apartmentId' : ApartmentId,
            'city' : IDL.Text,
            'name' : IDL.Text,
            'subscriptionStatus' : SubscriptionStatus,
            'superAdminId' : UserId,
          })
        ),
      ],
      ['query'],
    ),
  'getApartmentUsers' : IDL.Func([ApartmentId], [IDL.Vec(User)], ['query']),
  'getConsentRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConsentRecord)],
      ['query'],
    ),
  'getDisputeEscalations' : IDL.Func([], [Result_5], ['query']),
  'getDisputes' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(DisputeRecord)],
      ['query'],
    ),
  'getExpenses' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(ApartmentExpense)],
      ['query'],
    ),
  'getFacilityStatus' : IDL.Func(
      [ApartmentId],
      [IDL.Opt(FacilityStatus)],
      ['query'],
    ),
  'getFeedback' : IDL.Func([], [IDL.Vec(AppFeedback)], ['query']),
  'getFlats' : IDL.Func([ApartmentId], [IDL.Vec(Flat)], ['query']),
  'getFounderTeam' : IDL.Func([], [IDL.Vec(ProfileInfo)], ['query']),
  'getGuests' : IDL.Func([IDL.Text], [IDL.Vec(GuestRecord)], ['query']),
  'getInAppFeedback' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(FeedbackRecord)],
      ['query'],
    ),
  'getInchargeHistory' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(InchargeRecord)],
      ['query'],
    ),
  'getIssues' : IDL.Func([ApartmentId], [IDL.Vec(Issue)], ['query']),
  'getIssuesByFlat' : IDL.Func([FlatId], [IDL.Vec(Issue)], ['query']),
  'getMaintenanceForFlat' : IDL.Func(
      [FlatId],
      [IDL.Vec(MaintenancePayment)],
      ['query'],
    ),
  'getMoveOutChecklist' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MoveOutChecklist)],
      ['query'],
    ),
  'getMyMaintenancePayments' : IDL.Func(
      [],
      [IDL.Vec(MaintenancePayment)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNotices' : IDL.Func([ApartmentId], [IDL.Vec(Notice)], ['query']),
  'getNoticesForApartment' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'getNoticesForFamily' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getOpenTicketCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getParkingSlots' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(ParkingSlot)],
      ['query'],
    ),
  'getPaymentsByFlat' : IDL.Func(
      [FlatId],
      [IDL.Vec(MaintenancePayment)],
      ['query'],
    ),
  'getPendingPaymentConfirmations' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingPayments' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(MaintenancePayment)],
      ['query'],
    ),
  'getPendingWatchmanApprovals' : IDL.Func(
      [],
      [IDL.Vec(PendingWatchman)],
      ['query'],
    ),
  'getPlatformHealth' : IDL.Func([], [PlatformHealth], ['query']),
  'getSOSLog' : IDL.Func([ApartmentId], [IDL.Vec(SOSAlert)], ['query']),
  'getShiftHistory' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(WatchmanShift)],
      ['query'],
    ),
  'getSubscriptionTable' : IDL.Func([], [IDL.Vec(SubscriptionRow)], ['query']),
  'getSubscriptionsDueThisWeek' : IDL.Func([], [IDL.Nat], ['query']),
  'getTicketThread' : IDL.Func([IDL.Nat], [Result_4], ['query']),
  'getTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getUnreadNoticeCount' : IDL.Func([ApartmentId], [IDL.Nat], ['query']),
  'getVisitorLog' : IDL.Func([ApartmentId], [IDL.Vec(VisitorEntry)], ['query']),
  'getVisitorLogForFlat' : IDL.Func(
      [FlatId],
      [IDL.Vec(VisitorEntry)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([ApartmentId], [IDL.Nat], ['query']),
  'getWalletLedger' : IDL.Func(
      [ApartmentId],
      [IDL.Vec(WalletEntry)],
      ['query'],
    ),
  'getWalletSummaryForRole' : IDL.Func(
      [ApartmentId],
      [
        IDL.Record({
          'balance' : IDL.Int,
          'totalCollected' : IDL.Int,
          'entries' : IDL.Opt(IDL.Vec(WalletEntry)),
          'totalSpent' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getWatchmanFamily' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WatchmanFamilyMember)],
      ['query'],
    ),
  'initiateDebit' : IDL.Func([ApartmentId, IDL.Nat, IDL.Text], [Result], []),
  'initiateHandover' : IDL.Func(
      [ApartmentId, IDL.Text, HandoverChecklist],
      [Result],
      [],
    ),
  'initiateMovIn' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'initiateMovOut' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'isFounderRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listBillSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(BillSubscription)],
      ['query'],
    ),
  'listCalendarEvents' : IDL.Func(
      [],
      [IDL.Vec(FamilyCalendarEvent)],
      ['query'],
    ),
  'listDocuments' : IDL.Func([], [IDL.Vec(DocumentVaultEntry)], ['query']),
  'listFamilyContacts' : IDL.Func([], [IDL.Vec(FamilyContact)], ['query']),
  'listFamilyExpenses' : IDL.Func([], [IDL.Vec(FamilyExpense)], ['query']),
  'listFamilyTasks' : IDL.Func([], [IDL.Vec(FamilyTask)], ['query']),
  'listGroceryItems' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
  'listHealthRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
  'listReminders' : IDL.Func([], [IDL.Vec(FamilyReminder)], ['query']),
  'logVisitor' : IDL.Func(
      [IDL.Opt(FlatId), ApartmentId, IDL.Text, VisitorType, IDL.Text],
      [Result],
      [],
    ),
  'loginWithII' : IDL.Func([], [Result_3], []),
  'markResolved' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
  'postNotice' : IDL.Func(
      [ApartmentId, IDL.Text, IDL.Text, Priority],
      [Result],
      [],
    ),
  'raiseIssue' : IDL.Func(
      [FlatId, ApartmentId, IDL.Text, IDL.Text, IssueCategory],
      [Result],
      [],
    ),
  'recordConsent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerApartment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'registerWithInvite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'rejectDebit' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
  'rejectWatchmanId' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'reopenTicket' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
  'resolveDispute' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resolveSOS' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Text],
      [Result],
      [],
    ),
  'respondToSOS' : IDL.Func([IDL.Nat], [Result], []),
  'revokeGuest' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setNightMode' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'setUpiId' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result], []),
  'startShift' : IDL.Func([ApartmentId, UserId], [Result], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
  'submitInAppFeedback' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitPayment' : IDL.Func(
      [FlatId, ApartmentId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'submitWatchmanIdDoc' : IDL.Func([IDL.Text, WatchmanIdType], [Result], []),
  'triggerSOS' : IDL.Func([FlatId, ApartmentId, AlertType], [Result], []),
  'unassignParking' : IDL.Func([IDL.Nat], [Result], []),
  'updateApartmentUpi' : IDL.Func(
      [ApartmentId, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateBillSubscription' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, BillCategory, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateFacilityStatus' : IDL.Func(
      [ApartmentId, GateStatus, WaterMotorStatus, LiftStatus, CleaningStatus],
      [Result],
      [],
    ),
  'updateFamilyContact' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateFamilyExpense' : IDL.Func(
      [IDL.Nat, IDL.Nat, FamilyExpenseCategory, IDL.Text, Timestamp],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateFamilyTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Timestamp),
        TaskStatus,
        TaskPriority,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateGroceryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [Result], []),
  'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [Result], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [Result_1], ['query']),
  'verifyPayment' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApartmentId = IDL.Nat;
  const UserId = IDL.Nat;
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const BillCategory = IDL.Variant({
    'DTH' : IDL.Null,
    'Gas' : IDL.Null,
    'Internet' : IDL.Null,
    'Electricity' : IDL.Null,
    'Water' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const DocumentType = IDL.Variant({
    'PAN' : IDL.Null,
    'Insurance' : IDL.Null,
    'Aadhaar' : IDL.Null,
    'Vehicle' : IDL.Null,
    'Property' : IDL.Null,
    'Other' : IDL.Null,
  });
  const FamilyExpenseCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Bills' : IDL.Null,
    'Grocery' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Medical' : IDL.Null,
    'Other' : IDL.Null,
    'Transport' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const HealthRecordType = IDL.Variant({
    'Vaccination' : IDL.Null,
    'Report' : IDL.Null,
    'Other' : IDL.Null,
    'Prescription' : IDL.Null,
  });
  const RepeatType = IDL.Variant({
    'Weekly' : IDL.Null,
    'None' : IDL.Null,
    'Daily' : IDL.Null,
    'Monthly' : IDL.Null,
  });
  const FlatId = IDL.Nat;
  const Role = IDL.Variant({
    'RotatingIncharge' : IDL.Null,
    'Guest' : IDL.Null,
    'FamilyMember' : IDL.Null,
    'Employee' : IDL.Null,
    'Founder' : IDL.Null,
    'CoFounder' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'FlatAdmin' : IDL.Null,
    'Freelancer' : IDL.Null,
    'WatchmanFamily' : IDL.Null,
    'Watchman' : IDL.Null,
    'Contractor' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'Repair' : IDL.Null,
    'Salary' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Other' : IDL.Null,
    'Utilities' : IDL.Null,
  });
  const TicketCategory = IDL.Variant({
    'Bug' : IDL.Null,
    'Technical' : IDL.Null,
    'Billing' : IDL.Null,
    'Account' : IDL.Null,
    'Dispute' : IDL.Null,
    'Payment' : IDL.Null,
    'Other' : IDL.Null,
    'Feature' : IDL.Null,
  });
  const TicketPriority = IDL.Variant({
    'Normal' : IDL.Null,
    'Urgent' : IDL.Null,
  });
  const TicketType = IDL.Variant({
    'Support' : IDL.Null,
    'DisputeEscalation' : IDL.Null,
  });
  const ShiftHandoverChecklist = IDL.Record({
    'liftChecked' : IDL.Bool,
    'gateChecked' : IDL.Bool,
    'motorChecked' : IDL.Bool,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Record({ 'code' : IDL.Text, 'link' : IDL.Text }),
    'err' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({
      'expiresAt' : IDL.Int,
      'code' : IDL.Text,
      'link' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const WatchmanShift = IDL.Record({
    'id' : IDL.Nat,
    'startedAt' : Timestamp,
    'handoverChecklist' : ShiftHandoverChecklist,
    'apartmentId' : ApartmentId,
    'endedAt' : IDL.Opt(Timestamp),
    'isNightMode' : IDL.Bool,
    'relievedById' : IDL.Opt(UserId),
    'handoverNote' : IDL.Text,
    'watchmanId' : UserId,
  });
  const SubscriptionStatus = IDL.Variant({
    'GracePeriod' : IDL.Null,
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Overdue' : IDL.Null,
    'Trial' : IDL.Null,
  });
  const Apartment = IDL.Record({
    'id' : ApartmentId,
    'inchargeId' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'subscriptionStatus' : SubscriptionStatus,
    'address' : IDL.Text,
    'upiId' : IDL.Text,
    'upiQrData' : IDL.Text,
    'superAdminId' : UserId,
  });
  const User = IDL.Record({
    'id' : UserId,
    'principal' : IDL.Principal,
    'apartmentId' : IDL.Opt(ApartmentId),
    'flatId' : IDL.Opt(FlatId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const ConsentRecord = IDL.Record({
    'principal' : IDL.Principal,
    'watchmanGpsConsent' : IDL.Opt(IDL.Bool),
    'watchmanPhotoIdConsent' : IDL.Opt(IDL.Bool),
    'watchmanAttendanceConsent' : IDL.Opt(IDL.Bool),
    'generalConsent' : IDL.Bool,
    'generalConsentAt' : IDL.Int,
    'deviceInfo' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SlaMetadata = IDL.Record({
    'resolutionSla' : Timestamp,
    'firstResponseSla' : Timestamp,
    'breached' : IDL.Bool,
    'firstResponseAt' : IDL.Opt(Timestamp),
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const TicketStatus = IDL.Variant({
    'WaitingForUser' : IDL.Null,
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'sla' : SlaMetadata,
    'status' : TicketStatus,
    'assignedTo' : IDL.Opt(UserId),
    'subject' : IDL.Text,
    'apartmentId' : IDL.Opt(ApartmentId),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'ticketType' : TicketType,
    'category' : TicketCategory,
    'priority' : TicketPriority,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Vec(SupportTicket),
    'err' : IDL.Text,
  });
  const DisputeNote = IDL.Record({
    'note' : IDL.Text,
    'author' : IDL.Text,
    'addedAt' : IDL.Int,
  });
  const DisputeRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'flatId' : IDL.Text,
    'createdAt' : IDL.Int,
    'tier' : IDL.Nat,
    'description' : IDL.Text,
    'resolution' : IDL.Opt(IDL.Text),
    'notes' : IDL.Vec(DisputeNote),
    'category' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const ExpenseStatus = IDL.Variant({
    'Deducted' : IDL.Null,
    'Approved' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ApartmentExpense = IDL.Record({
    'id' : IDL.Nat,
    'status' : ExpenseStatus,
    'apartmentId' : ApartmentId,
    'approvedBy' : IDL.Vec(UserId),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : ExpenseCategory,
    'payee' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const CleaningStatus = IDL.Variant({
    'Done' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WaterMotorStatus = IDL.Variant({ 'On' : IDL.Null, 'Off' : IDL.Null });
  const LiftStatus = IDL.Variant({
    'OK' : IDL.Null,
    'Issue' : IDL.Null,
    'Offline' : IDL.Null,
  });
  const GateStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'Locked' : IDL.Null,
  });
  const FacilityStatus = IDL.Record({
    'cleaningStatus' : CleaningStatus,
    'apartmentId' : ApartmentId,
    'waterMotorStatus' : WaterMotorStatus,
    'liftStatus' : LiftStatus,
    'lastUpdatedAt' : Timestamp,
    'lastUpdatedBy' : UserId,
    'gateStatus' : GateStatus,
  });
  const AppFeedback = IDL.Record({
    'id' : IDL.Nat,
    'moduleName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const FlatStatus = IDL.Variant({
    'Vacant' : IDL.Null,
    'Occupied' : IDL.Null,
  });
  const Flat = IDL.Record({
    'id' : FlatId,
    'status' : FlatStatus,
    'ownerId' : IDL.Opt(UserId),
    'apartmentId' : ApartmentId,
    'tenantId' : IDL.Opt(UserId),
    'flatNumber' : IDL.Text,
  });
  const ProfileInfo = IDL.Record({
    'apartmentId' : IDL.Text,
    'flatId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const GuestRecord = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Int,
    'flatId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const FeedbackRecord = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'feedbackType' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Text,
    'screenshot' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const HandoverChecklist = IDL.Record({
    'gateKeyTransferred' : IDL.Bool,
    'upiUpdated' : IDL.Bool,
    'pendingIssuesNoted' : IDL.Bool,
    'ledgerReviewed' : IDL.Bool,
  });
  const InchargeRecord = IDL.Record({
    'id' : IDL.Nat,
    'handoverChecklist' : HandoverChecklist,
    'endDate' : IDL.Opt(Timestamp),
    'apartmentId' : ApartmentId,
    'userId' : UserId,
    'isActive' : IDL.Bool,
    'handoverNotes' : IDL.Text,
    'startDate' : Timestamp,
  });
  const IssueStatus = IDL.Variant({
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const IssueCategory = IDL.Variant({
    'Security' : IDL.Null,
    'Plumbing' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
    'Common' : IDL.Null,
  });
  const Issue = IDL.Record({
    'id' : IDL.Nat,
    'status' : IssueStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(UserId),
    'apartmentId' : ApartmentId,
    'flatId' : FlatId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : IssueCategory,
    'raisedBy' : UserId,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const PaymentStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const MaintenancePayment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'month' : IDL.Nat,
    'apartmentId' : ApartmentId,
    'flatId' : FlatId,
    'screenshotUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'correctionNote' : IDL.Opt(IDL.Text),
    'correctionOf' : IDL.Opt(IDL.Nat),
    'utrNumber' : IDL.Text,
    'amount' : IDL.Nat,
    'verifiedBy' : IDL.Opt(UserId),
  });
  const ChecklistEntry = IDL.Record({
    'item' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const MoveOutChecklist = IDL.Record({
    'completedAt' : IDL.Opt(IDL.Int),
    'flatId' : IDL.Text,
    'items' : IDL.Vec(ChecklistEntry),
    'initiatedAt' : IDL.Int,
  });
  const Priority = IDL.Variant({
    'Important' : IDL.Null,
    'Normal' : IDL.Null,
    'Urgent' : IDL.Null,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'postedBy' : UserId,
    'content' : IDL.Text,
    'acknowledgedBy' : IDL.Vec(UserId),
    'apartmentId' : ApartmentId,
    'priority' : Priority,
  });
  const ParkingType = IDL.Variant({
    'Car' : IDL.Null,
    'Bike' : IDL.Null,
    'Both' : IDL.Null,
  });
  const ParkingSlot = IDL.Record({
    'id' : IDL.Nat,
    'assignedAt' : IDL.Opt(Timestamp),
    'assignedTo' : IDL.Opt(FlatId),
    'apartmentId' : ApartmentId,
    'slotType' : ParkingType,
    'slotNumber' : IDL.Text,
  });
  const WatchmanStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WatchmanIdType = IDL.Variant({
    'Passport' : IDL.Null,
    'Aadhaar' : IDL.Null,
    'DrivingLicence' : IDL.Null,
    'VoterID' : IDL.Null,
    'Other' : IDL.Null,
  });
  const PendingWatchman = IDL.Record({
    'status' : WatchmanStatus,
    'principal' : IDL.Principal,
    'docUrl' : IDL.Text,
    'apartmentId' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'phone' : IDL.Text,
    'docType' : WatchmanIdType,
    'uploadedAt' : IDL.Int,
  });
  const PlatformHealth = IDL.Record({
    'activeUsers' : IDL.Nat,
    'cycleBalance' : IDL.Nat,
    'failedLogins' : IDL.Nat,
    'uptimePercent' : IDL.Nat,
    'sosCount' : IDL.Nat,
  });
  const AlertType = IDL.Variant({
    'Fire' : IDL.Null,
    'Safety' : IDL.Null,
    'Medical' : IDL.Null,
    'Other' : IDL.Null,
  });
  const SOSAlert = IDL.Record({
    'id' : IDL.Nat,
    'resolutionNote' : IDL.Text,
    'alertType' : AlertType,
    'apartmentId' : ApartmentId,
    'flatId' : FlatId,
    'isFalseAlarm' : IDL.Bool,
    'falseAlarmReason' : IDL.Text,
    'triggeredAt' : Timestamp,
    'triggeredBy' : UserId,
    'respondedAt' : IDL.Opt(Timestamp),
    'respondedBy' : IDL.Opt(UserId),
    'resolvedAt' : IDL.Opt(Timestamp),
    'resolvedBy' : IDL.Opt(UserId),
  });
  const SubscriptionRow = IDL.Record({
    'status' : SubscriptionStatus,
    'apartmentId' : ApartmentId,
    'city' : IDL.Text,
    'dueDate' : Timestamp,
    'adminUserId' : UserId,
    'utrSubmitted' : IDL.Bool,
    'flatsCount' : IDL.Nat,
    'apartmentName' : IDL.Text,
  });
  const TicketMessage = IDL.Record({
    'id' : IDL.Nat,
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'ticketId' : IDL.Nat,
    'message' : IDL.Text,
    'isInternal' : IDL.Bool,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Vec(TicketMessage),
    'err' : IDL.Text,
  });
  const VisitorType = IDL.Variant({
    'Guest' : IDL.Null,
    'Delivery' : IDL.Null,
    'Unknown' : IDL.Null,
    'Service' : IDL.Null,
  });
  const VisitorEntry = IDL.Record({
    'id' : IDL.Nat,
    'apartmentId' : ApartmentId,
    'flatId' : IDL.Opt(FlatId),
    'note' : IDL.Text,
    'visitorName' : IDL.Text,
    'visitorType' : VisitorType,
    'enteredAt' : Timestamp,
    'enteredBy' : UserId,
  });
  const DebitApprovalStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Executed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WalletEntryType = IDL.Variant({
    'Debit' : IDL.Null,
    'Correction' : IDL.Null,
    'Credit' : IDL.Null,
  });
  const WalletEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : DebitApprovalStatus,
    'entryType' : WalletEntryType,
    'apartmentId' : ApartmentId,
    'flatId' : IDL.Opt(FlatId),
    'approvedBy' : IDL.Vec(UserId),
    'createdAt' : Timestamp,
    'correctionNote' : IDL.Opt(IDL.Text),
    'correctionOf' : IDL.Opt(IDL.Nat),
    'utrNumber' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'purpose' : IDL.Text,
    'isPermanent' : IDL.Bool,
  });
  const WatchmanFamilyMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'phone' : IDL.Text,
    'watchmanId' : IDL.Text,
  });
  const BillSubscription = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'dueDay' : IDL.Nat,
    'category' : BillCategory,
    'amount' : IDL.Nat,
    'principalId' : IDL.Principal,
  });
  const FamilyCalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'reminder' : IDL.Opt(Timestamp),
    'date' : Timestamp,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const DocumentVaultEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'note' : IDL.Text,
    'docType' : DocumentType,
    'principalId' : IDL.Principal,
    'uploadedAt' : Timestamp,
    'fileUrl' : IDL.Text,
  });
  const FamilyContact = IDL.Record({
    'id' : IDL.Nat,
    'relation' : IDL.Text,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'phone' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const FamilyExpense = IDL.Record({
    'id' : IDL.Nat,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : FamilyExpenseCategory,
    'amount' : IDL.Nat,
    'principalId' : IDL.Principal,
  });
  const TaskStatus = IDL.Variant({ 'Done' : IDL.Null, 'Pending' : IDL.Null });
  const FamilyTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'priority' : TaskPriority,
    'principalId' : IDL.Principal,
  });
  const GroceryItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'isPurchased' : IDL.Bool,
    'addedAt' : Timestamp,
    'quantity' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Timestamp,
    'note' : IDL.Text,
    'recordType' : HealthRecordType,
    'memberName' : IDL.Text,
    'principalId' : IDL.Principal,
    'fileUrl' : IDL.Text,
  });
  const FamilyReminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'repeatType' : RepeatType,
    'date' : Timestamp,
    'time' : IDL.Text,
    'isActive' : IDL.Bool,
    'principalId' : IDL.Principal,
  });
  const Result_3 = IDL.Variant({ 'ok' : ProfileInfo, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({ 'role' : IDL.Text, 'isValid' : IDL.Bool }),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'acceptHandover' : IDL.Func([ApartmentId, UserId], [Result], []),
    'acknowledgeNotice' : IDL.Func([IDL.Nat], [Result], []),
    'addBillSubscription' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, BillCategory],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addCalendarEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Text, IDL.Opt(Timestamp)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addCorrectionEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [Result],
        [],
      ),
    'addDisputeNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addDocument' : IDL.Func(
        [IDL.Text, DocumentType, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addFamilyContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addFamilyExpense' : IDL.Func(
        [IDL.Nat, FamilyExpenseCategory, IDL.Text, Timestamp],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addFamilyTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Timestamp), TaskPriority],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addGroceryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addHealthRecord' : IDL.Func(
        [IDL.Text, HealthRecordType, IDL.Text, IDL.Text, Timestamp, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addInternalNote' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'addMessage' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'addReminder' : IDL.Func(
        [IDL.Text, Timestamp, IDL.Text, RepeatType],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addWatchmanFamilyMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'approveDebit' : IDL.Func([IDL.Nat], [Result], []),
    'approveExpense' : IDL.Func([IDL.Nat], [Result], []),
    'approveWatchmanId' : IDL.Func([IDL.Principal], [Result], []),
    'assignIncharge' : IDL.Func([ApartmentId, UserId, Timestamp], [Result], []),
    'assignParking' : IDL.Func([IDL.Nat, FlatId], [Result], []),
    'assignRole' : IDL.Func([IDL.Principal, Role], [Result], []),
    'completeChecklistItem' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'completeMovOut' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createApartment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'createDispute' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createExpense' : IDL.Func(
        [ApartmentId, IDL.Nat, ExpenseCategory, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createFlat' : IDL.Func([ApartmentId, IDL.Text], [Result], []),
    'createGuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createTicket' : IDL.Func(
        [IDL.Text, IDL.Text, TicketCategory, TicketPriority, TicketType],
        [Result],
        [],
      ),
    'createWatchmanInvite' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [Result], []),
    'deductExpense' : IDL.Func([IDL.Nat], [Result], []),
    'deleteBillSubscription' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteCalendarEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteDocument' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteFamilyContact' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteFamilyExpense' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteFamilyTask' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteGroceryItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteHealthRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteReminder' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'endShift' : IDL.Func(
        [IDL.Nat, IDL.Text, ShiftHandoverChecklist],
        [Result],
        [],
      ),
    'escalateDispute' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateFounderInvite' : IDL.Func([IDL.Text], [Result_7], []),
    'generateInviteCode' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Result_6],
        [],
      ),
    'getActiveShift' : IDL.Func(
        [ApartmentId],
        [IDL.Opt(WatchmanShift)],
        ['query'],
      ),
    'getActiveUpiId' : IDL.Func(
        [ApartmentId],
        [
          IDL.Opt(
            IDL.Record({
              'qrImageUrl' : IDL.Opt(IDL.Text),
              'upiId' : IDL.Text,
              'effectiveFrom' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getApartment' : IDL.Func([ApartmentId], [IDL.Opt(Apartment)], ['query']),
    'getApartmentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getApartmentOverview' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'apartmentId' : ApartmentId,
              'city' : IDL.Text,
              'name' : IDL.Text,
              'subscriptionStatus' : SubscriptionStatus,
              'superAdminId' : UserId,
            })
          ),
        ],
        ['query'],
      ),
    'getApartmentUsers' : IDL.Func([ApartmentId], [IDL.Vec(User)], ['query']),
    'getConsentRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConsentRecord)],
        ['query'],
      ),
    'getDisputeEscalations' : IDL.Func([], [Result_5], ['query']),
    'getDisputes' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(DisputeRecord)],
        ['query'],
      ),
    'getExpenses' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(ApartmentExpense)],
        ['query'],
      ),
    'getFacilityStatus' : IDL.Func(
        [ApartmentId],
        [IDL.Opt(FacilityStatus)],
        ['query'],
      ),
    'getFeedback' : IDL.Func([], [IDL.Vec(AppFeedback)], ['query']),
    'getFlats' : IDL.Func([ApartmentId], [IDL.Vec(Flat)], ['query']),
    'getFounderTeam' : IDL.Func([], [IDL.Vec(ProfileInfo)], ['query']),
    'getGuests' : IDL.Func([IDL.Text], [IDL.Vec(GuestRecord)], ['query']),
    'getInAppFeedback' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(FeedbackRecord)],
        ['query'],
      ),
    'getInchargeHistory' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(InchargeRecord)],
        ['query'],
      ),
    'getIssues' : IDL.Func([ApartmentId], [IDL.Vec(Issue)], ['query']),
    'getIssuesByFlat' : IDL.Func([FlatId], [IDL.Vec(Issue)], ['query']),
    'getMaintenanceForFlat' : IDL.Func(
        [FlatId],
        [IDL.Vec(MaintenancePayment)],
        ['query'],
      ),
    'getMoveOutChecklist' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MoveOutChecklist)],
        ['query'],
      ),
    'getMyMaintenancePayments' : IDL.Func(
        [],
        [IDL.Vec(MaintenancePayment)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNotices' : IDL.Func([ApartmentId], [IDL.Vec(Notice)], ['query']),
    'getNoticesForApartment' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'getNoticesForFamily' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getOpenTicketCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getParkingSlots' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(ParkingSlot)],
        ['query'],
      ),
    'getPaymentsByFlat' : IDL.Func(
        [FlatId],
        [IDL.Vec(MaintenancePayment)],
        ['query'],
      ),
    'getPendingPaymentConfirmations' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingPayments' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(MaintenancePayment)],
        ['query'],
      ),
    'getPendingWatchmanApprovals' : IDL.Func(
        [],
        [IDL.Vec(PendingWatchman)],
        ['query'],
      ),
    'getPlatformHealth' : IDL.Func([], [PlatformHealth], ['query']),
    'getSOSLog' : IDL.Func([ApartmentId], [IDL.Vec(SOSAlert)], ['query']),
    'getShiftHistory' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(WatchmanShift)],
        ['query'],
      ),
    'getSubscriptionTable' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionRow)],
        ['query'],
      ),
    'getSubscriptionsDueThisWeek' : IDL.Func([], [IDL.Nat], ['query']),
    'getTicketThread' : IDL.Func([IDL.Nat], [Result_4], ['query']),
    'getTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getUnreadNoticeCount' : IDL.Func([ApartmentId], [IDL.Nat], ['query']),
    'getVisitorLog' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(VisitorEntry)],
        ['query'],
      ),
    'getVisitorLogForFlat' : IDL.Func(
        [FlatId],
        [IDL.Vec(VisitorEntry)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([ApartmentId], [IDL.Nat], ['query']),
    'getWalletLedger' : IDL.Func(
        [ApartmentId],
        [IDL.Vec(WalletEntry)],
        ['query'],
      ),
    'getWalletSummaryForRole' : IDL.Func(
        [ApartmentId],
        [
          IDL.Record({
            'balance' : IDL.Int,
            'totalCollected' : IDL.Int,
            'entries' : IDL.Opt(IDL.Vec(WalletEntry)),
            'totalSpent' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getWatchmanFamily' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WatchmanFamilyMember)],
        ['query'],
      ),
    'initiateDebit' : IDL.Func([ApartmentId, IDL.Nat, IDL.Text], [Result], []),
    'initiateHandover' : IDL.Func(
        [ApartmentId, IDL.Text, HandoverChecklist],
        [Result],
        [],
      ),
    'initiateMovIn' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'initiateMovOut' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'isFounderRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listBillSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(BillSubscription)],
        ['query'],
      ),
    'listCalendarEvents' : IDL.Func(
        [],
        [IDL.Vec(FamilyCalendarEvent)],
        ['query'],
      ),
    'listDocuments' : IDL.Func([], [IDL.Vec(DocumentVaultEntry)], ['query']),
    'listFamilyContacts' : IDL.Func([], [IDL.Vec(FamilyContact)], ['query']),
    'listFamilyExpenses' : IDL.Func([], [IDL.Vec(FamilyExpense)], ['query']),
    'listFamilyTasks' : IDL.Func([], [IDL.Vec(FamilyTask)], ['query']),
    'listGroceryItems' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
    'listHealthRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
    'listReminders' : IDL.Func([], [IDL.Vec(FamilyReminder)], ['query']),
    'logVisitor' : IDL.Func(
        [IDL.Opt(FlatId), ApartmentId, IDL.Text, VisitorType, IDL.Text],
        [Result],
        [],
      ),
    'loginWithII' : IDL.Func([], [Result_3], []),
    'markResolved' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
    'postNotice' : IDL.Func(
        [ApartmentId, IDL.Text, IDL.Text, Priority],
        [Result],
        [],
      ),
    'raiseIssue' : IDL.Func(
        [FlatId, ApartmentId, IDL.Text, IDL.Text, IssueCategory],
        [Result],
        [],
      ),
    'recordConsent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerApartment' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'registerWithInvite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'rejectDebit' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
    'rejectWatchmanId' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'reopenTicket' : IDL.Func([IDL.Nat, IDL.Text], [Result_2], []),
    'resolveDispute' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resolveSOS' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Text],
        [Result],
        [],
      ),
    'respondToSOS' : IDL.Func([IDL.Nat], [Result], []),
    'revokeGuest' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setNightMode' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
    'setUpiId' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result], []),
    'startShift' : IDL.Func([ApartmentId, UserId], [Result], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
    'submitInAppFeedback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitPayment' : IDL.Func(
        [FlatId, ApartmentId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'submitWatchmanIdDoc' : IDL.Func([IDL.Text, WatchmanIdType], [Result], []),
    'triggerSOS' : IDL.Func([FlatId, ApartmentId, AlertType], [Result], []),
    'unassignParking' : IDL.Func([IDL.Nat], [Result], []),
    'updateApartmentUpi' : IDL.Func(
        [ApartmentId, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateBillSubscription' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, BillCategory, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateFacilityStatus' : IDL.Func(
        [ApartmentId, GateStatus, WaterMotorStatus, LiftStatus, CleaningStatus],
        [Result],
        [],
      ),
    'updateFamilyContact' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateFamilyExpense' : IDL.Func(
        [IDL.Nat, IDL.Nat, FamilyExpenseCategory, IDL.Text, Timestamp],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateFamilyTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Timestamp),
          TaskStatus,
          TaskPriority,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateGroceryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateIssueStatus' : IDL.Func([IDL.Nat, IssueStatus], [Result], []),
    'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [Result], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [Result_1], ['query']),
    'verifyPayment' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };